server:
  port: 8081 #为了不和前端服务冲突

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flexe_dispatch_sys?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: terry323
    driver-class-name: com.mysql.cj.jdbc.Driver
